default.xml: pin meta-freescale
The master branch of meta-freescale fails to build for WaRP7. I see this
error:

ERROR: rpb-console-image-1.0-r0 do_image_sdcard: imx7s-warp.dtb does not
exist.
ERROR: rpb-console-image-1.0-r0 do_image_sdcard: Function failed:
do_image_sdcard (log file is located at
/linaro/mbl/workspace/build-rpb/tmp-rpb-glibc/work/imx7s_warp-linaro-linux-gnueabi/rpb-console-image/1.0-r0/temp/log.do_image_sdcard.7790)
ERROR: Logfile of failure stored in:
/linaro/mbl/workspace/build-rpb/tmp-rpb-glibc/work/imx7s_warp-linaro-linux-gnueabi/rpb-console-image/1.0-r0/temp/log.do_image_sdcard.7790
ERROR: Task
(/linaro/mbl/workspace/build-rpb/conf/../../layers/meta-rpb/recipes-samples/images/rpb-console-image.bb:do_image_sdcard)
failed with exit code '1'

Bisect tells me it is this commit in meta-freescale:

  commit df8f4dafdf9ae9786d099d8c86985566e8c6e7da
  Author: Otavio Salvador <otavio@ossystems.com.br>
  Date:   Tue Sep 5 22:36:31 2017 -0300

    Stop using linux-dtb.inc

    The Device Tree support is now handled by the kernel class. This patch
    removes the inclusion of linux-dtb.inc from the kernel recipes in this
    layer.

    Change-Id: I3193f626b490af134e2691f02fc8655f78eb8621
    Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

This may be related to something else we've pinned, or to changes in
meta-mbl.

Signed-off-by: Ryan Harkin <ryan.harkin@linaro.org>